---
features:
  - |
    Support unrestricted attribute for application credentials

    * The unrestricted attribute is an optional flag to restrict whether the application credential may be used for the creation or destruction of other application credentials or trusts. Defaults to false.
