---
- hosts: controller
  tasks:
    - name: Add enable_plugin into local.conf
      shell:
        executable: /bin/bash
        cmd: |
          local_conf="/opt/stack/devstack/local.conf"
          sed -i '1a enable_plugin skyline-apiserver https://opendev.org/openstack/skyline-apiserver' $local_conf
          sed -i '1a enable_plugin neutron-vpnaas https://opendev.org/openstack/neutron-vpnaas' $local_conf
          sed -i '1a enable_plugin octavia https://opendev.org/openstack/octavia' $local_conf
          sed -i '1a enable_plugin neutron https://opendev.org/openstack/neutron' $local_conf
      become: yes

- hosts: all
  roles:
    - orchestrate-devstack
